/**
 * CANONICAL LIONSOFZION PARTICLE SOURCE BANK
 *
 * Mandatory source input:
 * - Exactly 28 word/phrase categories.
 * - Exactly 157 signal handles.
 * - Verbatim preservation of every canonical category, phrase, handle, character,
 *   capitalization choice, space, punctuation mark, and arrow.
 * - No external runtime file loading.
 */

export interface ParticleCategory {
  readonly id: string;
  readonly name: string;
  readonly weight: number;
  readonly phrases: readonly string[];
}

export const CANONICAL_CATEGORIES: readonly ParticleCategory[] = [
  {
    id: "core_identity",
    name: "Core Identity",
    weight: 1.2,
    phrases: [
      "TRUTH",
      "SIGNAL",
      "EVIDENCE",
      "INTELLIGENCE",
      "FACTS",
      "CONTEXT",
      "CLARITY",
      "CONFIDENCE",
      "KNOWLEDGE",
      "REALITY",
      "PROOF",
      "SOURCE",
      "SOURCES",
    ],
  },
  {
    id: "core_process",
    name: "Core Process",
    weight: 1.1,
    phrases: [
      "DETECT",
      "INVESTIGATE",
      "VERIFY",
      "EXPLAIN",
      "PROVE",
      "SHARE",
      "ANALYZE",
      "IDENTIFY",
      "TRACE",
      "CONNECT",
      "DOCUMENT",
      "ARCHIVE",
      "COMPARE",
      "REVIEW",
      "CONFIRM",
      "PUBLISH",
      "MONITOR",
    ],
  },
  {
    id: "verification",
    name: "Verification",
    weight: 1.15,
    phrases: [
      "VERIFIED",
      "UNVERIFIED",
      "CONFIRMED",
      "DISPUTED",
      "MISLEADING",
      "FALSE",
      "MANIPULATIVE",
      "OUT OF CONTEXT",
      "INCONCLUSIVE",
      "PARTIALLY TRUE",
      "EVIDENCE FOUND",
      "SOURCE VERIFIED",
      "CLAIM CHECKED",
    ],
  },
  {
    id: "fact_checking",
    name: "Fact Checking",
    weight: 1.1,
    phrases: [
      "FACT CHECK",
      "CLAIM",
      "CLAIMS",
      "EVIDENCE",
      "VERDICT",
      "RESPONSE",
      "PRIMARY SOURCE",
      "SECONDARY SOURCE",
      "ORIGINAL SOURCE",
      "SOURCE CHAIN",
      "CORROBORATION",
      "CONTRADICTION",
      "CONTEXT CHECK",
      "IMAGE CHECK",
      "VIDEO CHECK",
    ],
  },
  {
    id: "investigation",
    name: "Investigation",
    weight: 1.05,
    phrases: [
      "INVESTIGATION",
      "INVESTIGATIONS",
      "RESEARCH",
      "DEEP RESEARCH",
      "FINDINGS",
      "DISCOVERY",
      "CONNECTION",
      "NETWORK",
      "TIMELINE",
      "ENTITY",
      "ACTOR",
      "ACCOUNT",
      "ORGANIZATION",
      "EVENT",
      "LOCATION",
      "DOCUMENT",
      "RECORD",
      "ARCHIVE",
    ],
  },
  {
    id: "intelligence",
    name: "Intelligence",
    weight: 1.1,
    phrases: [
      "INTELLIGENCE",
      "PUBLIC INTELLIGENCE",
      "OPEN SOURCE",
      "OSINT",
      "SIGNAL DETECTION",
      "PATTERN",
      "PATTERNS",
      "INDICATOR",
      "INDICATORS",
      "ACTIVITY",
      "BEHAVIOR",
      "NETWORK ANALYSIS",
      "RELATIONSHIP",
      "CONNECTIONS",
      "MONITORING",
    ],
  },
  {
    id: "information_environment",
    name: "Information Environment",
    weight: 1.0,
    phrases: [
      "INFORMATION",
      "INFORMATION WARFARE",
      "INFORMATION OPERATIONS",
      "INFLUENCE",
      "INFLUENCE NETWORK",
      "NARRATIVE",
      "NARRATIVES",
      "MEDIA",
      "MESSAGE",
      "MESSAGING",
      "AMPLIFICATION",
      "DISTRIBUTION",
      "VIRALITY",
      "REACH",
    ],
  },
  {
    id: "disinformation",
    name: "Disinformation",
    weight: 1.0,
    phrases: [
      "DISINFORMATION",
      "MISINFORMATION",
      "PROPAGANDA",
      "MANIPULATION",
      "DECEPTION",
      "FABRICATION",
      "DISTORTION",
      "FALSE CLAIM",
      "FALSE NARRATIVE",
      "COORDINATED ACTIVITY",
      "INAUTHENTIC BEHAVIOR",
      "IMPERSONATION",
      "BOT",
      "BOTS",
      "TROLL",
      "TROLLS",
    ],
  },
  {
    id: "detection",
    name: "Detection",
    weight: 1.05,
    phrases: [
      "DETECTED",
      "FLAGGED",
      "TRACKED",
      "OBSERVED",
      "CAPTURED",
      "INDEXED",
      "MATCHED",
      "LINKED",
      "CLUSTERED",
      "ESCALATING",
      "EMERGING",
      "ACTIVE",
      "WATCHING",
      "MONITORING",
      "SCANNING",
    ],
  },
  {
    id: "evidence",
    name: "Evidence",
    weight: 1.15,
    phrases: [
      "EVIDENCE",
      "RECEIPTS",
      "DOCUMENTATION",
      "SCREENSHOT",
      "ARCHIVE",
      "RECORD",
      "DATA",
      "METADATA",
      "SOURCE",
      "LINK",
      "CITATION",
      "TIMESTAMP",
      "LOCATION",
      "ORIGIN",
      "HASH",
      "CAPTURE",
      "PROVENANCE",
    ],
  },
  {
    id: "news",
    name: "News",
    weight: 1.0,
    phrases: [
      "TODAY",
      "NEWS",
      "BREAKING",
      "DEVELOPING",
      "LATEST",
      "UPDATE",
      "LIVE",
      "LIVE UPDATES",
      "DAILY BRIEF",
      "BRIEFING",
      "HEADLINE",
      "STORY",
      "STORIES",
      "REPORT",
      "REPORTING",
      "EVENT",
      "EVENTS",
    ],
  },
  {
    id: "israel",
    name: "Israel",
    weight: 1.1,
    phrases: [
      "ISRAEL",
      "ISRAEL EXPLAINED",
      "ZION",
      "ZIONISM",
      "JEWISH HISTORY",
      "JEWISH PEOPLE",
      "JERUSALEM",
      "MIDDLE EAST",
      "ISRAELI SOCIETY",
      "SECURITY",
      "HISTORY",
      "IDENTITY",
      "SOVEREIGNTY",
    ],
  },
  {
    id: "october_7",
    name: "October 7",
    weight: 1.1,
    phrases: [
      "OCTOBER 7",
      "TESTIMONY",
      "TESTIMONIES",
      "SURVIVORS",
      "HOSTAGES",
      "VICTIMS",
      "HEROES",
      "DOCUMENTATION",
      "ARCHIVE",
      "TIMELINE",
      "EVIDENCE",
      "FOOTAGE",
      "RECORDS",
      "STORIES",
    ],
  },
  {
    id: "analysis",
    name: "Analysis",
    weight: 1.05,
    phrases: [
      "ANALYSIS",
      "EXPLANATION",
      "CONTEXT",
      "BACKGROUND",
      "WHY IT MATTERS",
      "WHAT CHANGED",
      "WHAT WE KNOW",
      "WHAT WE DON'T KNOW",
      "KEY FINDINGS",
      "ASSESSMENT",
      "CONFIDENCE",
      "IMPACT",
    ],
  },
  {
    id: "network",
    name: "Network",
    weight: 1.0,
    phrases: [
      "NETWORK",
      "NODE",
      "NODES",
      "EDGE",
      "EDGES",
      "CONNECTION",
      "CONNECTIONS",
      "RELATIONSHIP",
      "RELATIONSHIPS",
      "CLUSTER",
      "CLUSTERS",
      "SOURCE",
      "TARGET",
      "AMPLIFIER",
      "ACTOR",
      "ENTITY",
      "FLOW",
    ],
  },
  {
    id: "signal",
    name: "Signal",
    weight: 1.15,
    phrases: [
      "SIGNAL",
      "NOISE",
      "SIGNAL OVER NOISE",
      "DETECTION",
      "PULSE",
      "TRACE",
      "PATTERN",
      "STREAM",
      "FEED",
      "INPUT",
      "OUTPUT",
      "SOURCE",
      "MATCH",
      "ALERT",
      "WATCH",
      "LIVE SIGNAL",
    ],
  },
  {
    id: "editorial",
    name: "Editorial",
    weight: 0.95,
    phrases: [
      "STORY",
      "ARTICLE",
      "REPORT",
      "INVESTIGATION",
      "EXPLAINER",
      "BRIEF",
      "ANALYSIS",
      "OPINION",
      "DOCUMENTATION",
      "TIMELINE",
      "PROFILE",
      "DOSSIER",
      "CASE FILE",
      "SOURCE NOTE",
    ],
  },
  {
    id: "research_states",
    name: "Research States",
    weight: 1.0,
    phrases: [
      "DETECTED",
      "IN REVIEW",
      "INVESTIGATING",
      "VERIFYING",
      "VERIFIED",
      "PUBLISHED",
      "UPDATED",
      "ARCHIVED",
      "MONITORING",
    ],
  },
  {
    id: "confidence",
    name: "Confidence",
    weight: 1.05,
    phrases: [
      "HIGH CONFIDENCE",
      "MEDIUM CONFIDENCE",
      "LOW CONFIDENCE",
      "CONFIRMED",
      "LIKELY",
      "POSSIBLE",
      "UNKNOWN",
      "UNRESOLVED",
      "INSUFFICIENT EVIDENCE",
    ],
  },
  {
    id: "actions",
    name: "Actions",
    weight: 0.95,
    phrases: [
      "SEARCH",
      "ASK AI",
      "EXPLORE",
      "READ",
      "VERIFY",
      "INVESTIGATE",
      "OPEN SOURCE",
      "VIEW EVIDENCE",
      "SEE SOURCES",
      "FOLLOW LIVE",
      "SHARE",
      "COPY",
      "DOWNLOAD",
      "SAVE",
    ],
  },
  {
    id: "system",
    name: "System",
    weight: 1.0,
    phrases: [
      "SYSTEM",
      "ENGINE",
      "PIPELINE",
      "WORKFLOW",
      "PROCESS",
      "AGENT",
      "AGENTS",
      "TASK",
      "TASKS",
      "QUEUE",
      "STATUS",
      "RUN",
      "EVENT",
      "LOG",
      "SOURCE",
      "SCAN",
      "QUERY",
      "RESULT",
    ],
  },
  {
    id: "operational",
    name: "Operational",
    weight: 0.9,
    phrases: [
      "ACTIVE",
      "IDLE",
      "RUNNING",
      "COMPLETE",
      "FAILED",
      "QUEUED",
      "PROCESSING",
      "WAITING",
      "RETRYING",
      "CONNECTED",
      "DISCONNECTED",
      "HEALTHY",
      "DEGRADED",
    ],
  },
  {
    id: "publication",
    name: "Publication",
    weight: 1.0,
    phrases: [
      "PUBLIC",
      "PUBLISHED",
      "UPDATED",
      "CORRECTED",
      "SOURCED",
      "DOCUMENTED",
      "TRANSPARENT",
      "ACCOUNTABLE",
      "TRACEABLE",
      "SHAREABLE",
    ],
  },
  {
    id: "mission",
    name: "Mission",
    weight: 1.2,
    phrases: [
      "DEFEND THE TRUTH",
      "EXPOSE THE FALSE",
      "FOLLOW THE EVIDENCE",
      "FIND THE SIGNAL",
      "VERIFY BEFORE AMPLIFYING",
      "SHOW THE SOURCE",
      "PROVE THE CLAIM",
      "UNDERSTAND THE NETWORK",
    ],
  },
  {
    id: "brand_phrases",
    name: "Brand Phrases",
    weight: 1.25,
    phrases: [
      "TRUTH HAS A SIGNAL",
      "TRUTH OVER NOISE",
      "EVIDENCE OVER EMOTION",
      "FACTS OVER NARRATIVES",
      "DETECT THE FALSE",
      "EXPOSE THE LIES",
      "DEFEND THE TRUTH",
    ],
  },
  {
    id: "platform_areas",
    name: "Platform Areas",
    weight: 1.0,
    phrases: [
      "TODAY",
      "FACT CHECKS",
      "INVESTIGATIONS",
      "OCTOBER 7",
      "ISRAEL EXPLAINED",
      "ABOUT",
      "SEARCH",
      "ASK AI",
      "LIVE UPDATES",
    ],
  },
  {
    id: "extended_platform",
    name: "Extended Platform",
    weight: 1.05,
    phrases: [
      "PUBLIC INTELLIGENCE",
      "NEWS MONITORING",
      "FACT CHECKING",
      "EVIDENCE-BASED INVESTIGATIONS",
      "DISINFORMATION RESEARCH",
      "ISRAEL EXPLAINERS",
      "OCTOBER 7 DOCUMENTATION",
      "PUBLIC COMMUNICATION",
      "INTERNAL RESEARCH OPERATIONS",
      "PROJECT OBSERVABILITY",
      "AGENT OBSERVABILITY",
    ],
  },
  {
    id: "core_workflow",
    name: "Core Workflow",
    weight: 1.2,
    phrases: [
      "DETECT → INVESTIGATE → VERIFY → EXPLAIN → PROVE → SHARE",
    ],
  },
] as const;

export const CANONICAL_HANDLES: readonly string[] = [
  "@khamenei_ir",
  "@Rahbarenghelab_",
  "@drpezeshkian",
  "@mb_ghalibaf",
  "@araghchi",
  "@IRIMFA_SPOX",
  "@ejei_org",
  "@ir_rezaee",
  "@IranMFA",
  "@AmbIranUN",
  "@JZarif",
  "@PressTV",
  "@PresstvExtra",
  "@TasnimNews",
  "@Tasnimbrk",
  "@tasnim_pal",
  "@FarsNews_En",
  "@IRNA_English",
  "@alalam_ar",
  "@HispanTV",
  "@IRINN",
  "@iribnews_irib",
  "@TehranTimes",
  "@MehrNewsEn",
  "@KayhanIran",
  "@JavanOnline",
  "@Sepah",
  "@IRGC_Press",
  "@IRGC_Global",
  "@GBC_Press",
  "@GBX_Press",
  "@GP_Presss",
  "@SPC_Press",
  "@Expres_Newsx",
  "@TNT_Today",
  "@OpsHQs",
  "@IR_HDX",
  "@Iran__Fire",
  "@SPX_Press",
  "@IRIran_Military",
  "@jacksonhinklle",
  "@MaxBlumenthal",
  "@TheGrayzoneNews",
  "@AaronjMate",
  "@RaniaKhalek",
  "@AnyaParampil",
  "@wyattreed13",
  "@KitKlarenberg",
  "@BenjaminNorton",
  "@DanCohen3000",
  "@RealAlexRubi",
  "@AlanRMacLeod",
  "@MintPressNews",
  "@MnarMuhawesh",
  "@RobertInlakesh",
  "@_whitneywebb",
  "@EvaBartlett",
  "@VanessaBeeley",
  "@Lowkey0nline",
  "@RichardMedhurst",
  "@caitoz",
  "@AliAbunimah",
  "@AsaWinstanley",
  "@NoraBarrows",
  "@intifada",
  "@AbbyMartin",
  "@AssalRad",
  "@sahouraxo",
  "@HussainShafiei",
  "@DannyHaiphong",
  "@BrianJBerletic",
  "@RealScottRitter",
  "@RealPepeEscobar",
  "@GeorgeGalloway",
  "@CalebMaupin",
  "@GarlandNixon",
  "@Helga_Zepp",
  "@JeffreySachs",
  "@JohnMearsheimer",
  "@Glenn_Diesen",
  "@PatrickHenningsen",
  "@GrahamWPhillips",
  "@AlinaLipp",
  "@DanBilzerian",
  "@GretaThunberg",
  "@Byoussef",
  "@RealCandaceO",
  "@abdelbariatwan",
  "@omarsuleiman",
  "@DrLoupis",
  "@NickJFuentes",
  "@IanCarrollShow",
  "@TuckerCarlson",
  "@JakeShields",
  "@CensoredMen",
  "@LucasGage_",
  "@Sneako",
  "@MyronGaines_",
  "@Clavicular",
  "@Cobratate",
  "@FrancescaAlbanese",
  "@ZohranKMamdani",
  "@msrachelforlittles",
  "@MarkRuffalo",
  "@mohammedelkurd",
  "@NerdeenKiswani",
  "@WithinOurLifetime",
  "@SJPNational",
  "@BDSNational",
  "@IfNotNowOrg",
  "@JVPNews",
  "@CodePink",
  "@MedeaBenjamin",
  "@SamidounNetwork",
  "@PFLP_EN",
  "@AnsarAllah",
  "@HouthiMovement",
  "@HamasInfoEn",
  "@QudsNen",
  "@qudsn",
  "@AlQassam_Brigade",
  "@ShehabAgency",
  "@PalinfoEn",
  "@Hezbollah",
  "@AlManarNews",
  "@AlMayadeen",
  "@AlMayadeenEn",
  "@KataibHezbollah",
  "@SputnikInt",
  "@RT_com",
  "@RTarabic",
  "@RTenespanol",
  "@XinhuaChinese",
  "@CGTNOfficial",
  "@globaltimesnews",
  "@mfa_russia",
  "@RusEmbUSA",
  "@mod_russia",
  "@MedvedevRussiaE",
  "@ZakharovaMaria",
  "@OwenJones84",
  "@hasanthehun",
  "@cenkuygur",
  "@normfinkelstein",
  "@IlanPappe",
  "@judithbutler",
  "@NaomiAKlein",
  "@AngelaDavis",
  "@TariqAli63",
  "@sallyrooney",
  "@GeorgeMonbiot",
  "@BreakThroughNews",
  "@PSCupdates",
  "@MikoPeled",
  "@GhassanAbuSitta",
  "@HelenaCobban",
  "@DropSiteNews",
] as const;

export const EXACT_CATEGORY_COUNT = 28;
export const EXACT_HANDLE_COUNT = 157;

/**
 * Validation helper to prove that all 28 categories and 157 handles are loaded.
 */
export function validateParticleBank(): {
  readonly valid: boolean;
  readonly categoryCount: number;
  readonly handleCount: number;
  readonly errors: readonly string[];
} {
  const errors: string[] = [];
  if (CANONICAL_CATEGORIES.length !== EXACT_CATEGORY_COUNT) {
    errors.push(
      `Expected exactly ${EXACT_CATEGORY_COUNT} categories, found ${CANONICAL_CATEGORIES.length}`
    );
  }
  if (CANONICAL_HANDLES.length !== EXACT_HANDLE_COUNT) {
    errors.push(
      `Expected exactly ${EXACT_HANDLE_COUNT} handles, found ${CANONICAL_HANDLES.length}`
    );
  }

  // Ensure no empty categories or strings
  for (const cat of CANONICAL_CATEGORIES) {
    if (!cat.name || cat.phrases.length === 0) {
      errors.push(`Category "${cat.name || cat.id}" has no phrases.`);
    }
    for (const phrase of cat.phrases) {
      if (!phrase || phrase.trim().length === 0) {
        errors.push(`Category "${cat.name}" contains an empty phrase.`);
      }
    }
  }

  for (const handle of CANONICAL_HANDLES) {
    if (!handle || !handle.startsWith("@")) {
      errors.push(`Invalid handle format: "${handle}"`);
    }
  }

  return {
    valid: errors.length === 0,
    categoryCount: CANONICAL_CATEGORIES.length,
    handleCount: CANONICAL_HANDLES.length,
    errors,
  };
}

/**
 * Extracts all unique characters present in the entire canonical corpus
 * (categories + handles).
 */
export function getCanonicalCorpusGlyphs(): readonly string[] {
  const glyphSet = new Set<string>();
  // Space is always included as separator
  glyphSet.add(" ");

  for (const cat of CANONICAL_CATEGORIES) {
    for (const phrase of cat.phrases) {
      for (const char of phrase) {
        glyphSet.add(char);
      }
    }
  }

  for (const handle of CANONICAL_HANDLES) {
    for (const char of handle) {
      glyphSet.add(char);
    }
  }

  return Array.from(glyphSet).sort();
}
