import type { NodeKind } from "./types";

export type NodeInspectorCopy = {
  what: string;
  why: string;
  input: string;
  does: string;
  output: string;
  failureMode: string;
};

export type GlossaryTermCopy = {
  short: string;
  deep: string;
  example?: string;
};

export const KIND_LABELS: Record<NodeKind, string> = {
  source: "Data source",
  table: "Database table",
  view: "Read view",
  guard: "Guard",
  trigger: "SQL trigger",
  cron: "Cron",
  queue: "Queue",
  connector: "Connector",
  service: "Service",
  model: "Language model",
  gateway: "AI gateway",
  storage: "Blob storage",
};

export const LANE_COPY = [
  {
    id: "ingest",
    title: "1. Ingestion & raw blob",
    description: "Capture source pages, compute SHA-256, and block duplicates",
    laneIndex: 0,
  },
  {
    id: "evidence",
    title: "2. Evidence & claims",
    description: "Record items, cross-check facts, and keep provenance",
    laneIndex: 1,
  },
  {
    id: "model",
    title: "3. Verification & publish gate",
    description: "Pure rules engine and a two-human gate before the public",
    laneIndex: 2,
  },
  {
    id: "briefing",
    title: "4. Daily brief pipeline",
    description: "Collect, cluster, triage, draft, and publish at 07:00",
    laneIndex: 3,
  },
  {
    id: "search",
    title: "5. Search & outbox",
    description: "Transactional outbox, multilingual index, and embeddings",
    laneIndex: 4,
  },
  {
    id: "ai",
    title: "6. AI gateway & grounded chat",
    description: "Document-grounded answers with a citation guard against hallucination",
    laneIndex: 5,
  },
  {
    id: "infra",
    title: "7. Governance, RLS & public",
    description: "Row-level security, rate limits, and public reports",
    laneIndex: 6,
  },
] as const;

export const GLOSSARY_CATEGORY_LABELS: Record<string, string> = {
  all: "All terms",
  ingest: "Ingest & sources",
  evidence: "Evidence & claims",
  model: "Verification & rules",
  briefing: "Daily brief",
  search: "Search & outbox",
  ai: "Artificial intelligence",
  infra: "Infrastructure & security",
};

export const CHROME = {
  brandBadge: "System architecture and information pipeline",
  headerSubtitle:
    "A scripted interactive simulation of the claim-verification engine, SQL gates, daily brief machine, and security layers — derived from the codebase, not a live run",
  glossaryButton: "Glossary",
  glossaryButtonTitle: "Open the glossary",
  viewAllPipelines: "Full system (7 lanes)",
  viewBriefing: "Daily brief machine",
  prevStep: "Previous step",
  nextStep: "Next step",
  play: "Play",
  pause: "Pause",
  reset: "Reset simulation",
  stepOf: (current: number, total: number) => `Step ${current} of ${total}`,
  stepAria: (index: number, title: string) => `Step ${index}: ${title}`,
  nowHappening: "What is happening now",
  activeComponent: "Active component",
  table: "Table",
  sqlConstraint: "SQL constraint",
  payloadHeader: "Payload on this hop",
  collapse: "Collapse",
  expand: "Expand",
  collapseTitle: "Collapse explanation",
  expandTitle: "Expand explanation",
  telemetrySimulated: "Scripted simulation — not live telemetry",
  currentStep: "Current step",
  waitingToStart: "Waiting to start",
  logEmpty: "Waiting for simulation ticks…",
  logLevel: {
    error: "Error",
    warn: "Warning",
    success: "Success",
    info: "Info",
  },
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  resetView: "Reset view",
  fitAll: "Fit all",
  spacing: "Card spacing",
  compact: "Compact",
  comfortable: "Comfortable",
  extraWide: "Extra wide",
  rearrange: "Reset layout",
  rearrangeTitle: "Return cards to the automatic layout",
  canvasHint: "Scroll to pan · hold Ctrl/Cmd and scroll to zoom · drag cards to reposition",
  lane: (n: number) => `Lane ${n}`,
  explain: "Explain",
  explainTitle: "Open this term in the glossary",
  inspectorClose: "Close inspector",
  inspectorWhat: "What this component does",
  inspectorWhy: "Why it is built this way",
  inspectorInput: "Inputs",
  inspectorDoes: "What it does",
  inspectorOutput: "Outputs",
  inspectorFailure: "Failure mode",
  inspectorTable: "Database table",
  inspectorSql: "SQL constraint or trigger",
  inspectorCode: "Source reference",
  inspectorTerms: "Related terms",
  glossaryTitle: "Glossary",
  glossarySubtitle: "Technical terms, models, and tables in the system architecture.",
  glossaryClose: "Close glossary",
  glossarySearch: "Search a term (for example: Outbox, RLS, embeddings)…",
  glossaryEmpty: (query: string) => `No terms match “${query}”.`,
  glossaryTable: "Table",
  glossaryDeep: "Engineering notes",
  glossaryExample: "Example in this system",
} as const;

export const NODE_COPY: Record<string, NodeInspectorCopy> = {
  family: {
    what: "Groups sources under one journalistic entity — for example every Reuters desk, or Agence France-Presse.",
    why: "Five sites rewriting one wire are not five independent confirmations. Verification counts families, not URLs.",
    input: "An editor’s manual definition when a new source is registered.",
    does: "Binds every active source to exactly one family.",
    output: "A stable mapping that blocks the illusion of independent corroboration.",
    failureMode: "A family drawn too wide drops real confirmations; too narrow and reprints of the same report are counted twice.",
  },
  source: {
    what: "A live collection channel: an RSS feed URL, a GDELT query, or a search against approved agencies.",
    why: "Every fetch needs an address, a cadence, and a consecutive-failure counter so a downed host is not hammered.",
    input: "URL, connector kind, source family, and collection frequency.",
    does: "Tracks consecutive_failures and disables the source after five failures in a row.",
    output: "A source entity ready for periodic scan.",
    failureMode: "A source that fails five times is disabled so it cannot stall the ingest queues.",
  },
  cron_ingest: {
    what: "A Vercel Cron job that kicks off a scan of every active source.",
    why: "Continuous collection without a human in the loop, so reports surface in near-real time.",
    input: "An HTTP call authenticated with CRON_SECRET from Vercel.",
    does: "Samples active sources by last-run time and hands them to connectors.",
    output: "A scan started for every due source.",
    failureMode: "If the tick misses, the queue lags until the next run; nothing already stored is lost.",
  },
  connector: {
    what: "Code that pulls from the network, parses XML/JSON, and extracts items.",
    why: "Fetch and parse run outside the database transaction so a slow network cannot lock tables.",
    input: "An HTTP request to an external source.",
    does: "Fetches content, extracts metadata, and computes SHA-256 of the raw bytes.",
    output: "A raw payload plus a set of normalised records.",
    failureMode: "A network or parse error is recorded on source_fetch as failed or partial.",
  },
  blob_storage: {
    what: "Private object storage holding the full response body exactly as received.",
    why: "If a year from now someone claims a misquote, the original bytes and SHA-256 are still there.",
    input: "The raw network response.",
    does: "Writes an immutable object to Blob Storage and returns a signed URL.",
    output: "A durable URL and a sha256 content hash.",
    failureMode: "restricted/secret material is blocked from Blob upload by a classification check.",
  },
  source_fetch: {
    what: "An append-only table logging every fetch attempt: when, how many items were seen, how many were new, and errors.",
    why: "Item and evidence counts are written in the same transaction as the evidence itself — a count that does not match reality is worse than no row.",
    input: "The connector’s scan result.",
    does: "Records status (success, partial, failed) and the raw content hash.",
    output: "An audit trail of source health.",
    failureMode: "Append-only — fetch rows cannot be deleted or edited.",
  },
  evidence_discovery: {
    what: "A table mapping every external id, canonical URL, and content hash to existing evidence.",
    why: "Stops duplicate evidence when a feed is rescanned or the same article appears at different URLs.",
    input: "Link, title, external GUID, and normalised content.",
    does: "Checks duplicates four ways: new, external_id, canonical_url, content_hash.",
    output: "A link to existing evidence, or clearance to create a new row.",
    failureMode: "A duplicate is recorded as another discovery without cloning the evidence.",
  },
  evidence: {
    what: "The collected facts and sources — cleaned text, quotes, metadata, and classification.",
    why: "Evidence is the building block. An information item does not stand alone; it rests on linked evidence.",
    input: "A new item that has already been de-duplicated.",
    does: "Stores usable text, a data_class (public..secret), and the source family.",
    output: "A unique evidence row with a UUID.",
    failureMode: "Classified evidence cannot be exposed to the public or sent to language models.",
  },
  evidence_provenance: {
    what: "A table recording who imported the evidence, from which source, and by which path.",
    why: "In a verification system it matters which service or person put the material in the store.",
    input: "Fetch details and the actor.",
    does: "Writes an immutable arrival path.",
    output: "A full provenance trail.",
    failureMode: "Append-only.",
  },
  item: {
    what: "The claim or event under review: canonical source wording, item type, and workflow status.",
    why: "Text is stored as said, not paraphrased, so verification addresses the claim rather than an editor’s rewrite.",
    input: "A new claim from an analyst or an automatic extract.",
    does: "Manages a status lifecycle completely separate from the assessment verdict.",
    output: "A versioned information item.",
    failureMode: "An illegal status change is blocked by the status_transition trigger.",
  },
  status_axes: {
    what: "A hard split between the workflow axis (status) and the verdict axis (assessment).",
    why: "An item can be published and false, or still in review and verified. Merging the axes would force a fake verdict before the check finished.",
    input: "Requested status and assessment values.",
    does: "Keeps queue position independent of the check’s result.",
    output: "A faithful picture of what is actually known.",
    failureMode: "There is no way to represent an item without separating process from finding.",
  },
  item_evidence: {
    what: "Links evidence to an item with a relation (supports/contradicts/context), strength, and a required rationale.",
    why: "A link without a rationale is not journalism. The rules engine also counts a link only after human confirmation (confirmed_by).",
    input: "An evidence-to-claim assignment with a reasoned argument.",
    does: "Records relation, strength, rationale, and a human confirmation stamp.",
    output: "A reasoned edge in the evidence graph.",
    failureMode: "An unconfirmed link does not count toward verdict eligibility.",
  },
  verdict_rules: {
    what: "A pure function that computes which verdicts are allowed from supporting and contradicting source families.",
    why: "Stops human error: a verified verdict needs at least two independent supporting families and zero contradicting ones.",
    input: "Confirmed links and their source families.",
    does: "Computes allowedVerdicts and freezes a snapshot on the assessment.",
    output: "Allow or refuse the requested verdict.",
    failureMode: "Persisting a verdict without evidential support is rejected as VALIDATION_ERROR.",
  },
  item_assessment: {
    what: "The official verdict: conclusion, editorial rationale, unresolved gaps, and a 10-dimension confidence matrix.",
    why: "A single score such as 0.85 hides weakness. Ten verbal dimensions show exactly where the record is strong and where it is thin.",
    input: "A verdict and rationale from a qualified analyst.",
    does: "Stores the confidence dimensions and freezes the eligibility snapshot that was in force when it was written.",
    output: "A signed, versioned assessment.",
    failureMode: "The previous assessment is marked superseded when a new one is written.",
  },
  review_queue: {
    what: "A peer-review task queue — assessments and items waiting for a second person.",
    why: "No assessment is published by its author alone. A second pair of eyes must confirm.",
    input: "An assessment written by an analyst.",
    does: "Tracks handling states (open, claimed, blocked, done, dropped).",
    output: "An assessment reviewed by an independent reviewer.",
    failureMode: "Self-review is blocked — the author cannot claim their own task.",
  },
  enforce_publish_gate: {
    what: "A database trigger that refuses published status unless two different humans have acted.",
    why: "Iron rule: the author cannot be the approver, and a model may not approve on the manual path.",
    input: "A status update to published.",
    does: "Checks for an approved review by a human who is not the creator and not an automated identity.",
    output: "Clearance to enter published status.",
    failureMode: "The whole Postgres transaction is aborted.",
  },
  published_item_view: {
    what: "A SQL view returning only published items with their active assessment and confirmed evidence.",
    why: "The public and search queries go through this view, so in-review items simply do not exist for an outside reader.",
    input: "A public read query.",
    does: "Filters by RLS and publish status and joins only confirmed evidence.",
    output: "Complete, verified public rows.",
    failureMode: "No leak of drafts or rejected assessments.",
  },
  publication: {
    what: "Public editorial surfaces: daily brief, news update, geopolitical analysis, and scenario. Live sections are daily_brief, israel_update, and narrative_watch.",
    why: "Every surface shares versioning, the publish gate, and links to verified items and sourced passages.",
    input: "A structured editorial product with passages and linked sources.",
    does: "Stores the text, sectioning, and explicit pointers to items and evidence.",
    output: "A public publication page. war_update remains a legal schema value for the archive and is no longer produced — /war-update still serves what was written there and stops growing.",
    failureMode: "A scenario must carry a verbal likelihoodBand and is forbidden from carrying numeric percentages.",
  },
  cron_briefing: {
    what: "A scheduler that wakes every 15 minutes in the 04:00–05:45 UTC windows and detects 07:00 in Jerusalem.",
    why: "Automatic morning-brief production independent of daylight-saving shifts.",
    input: "Wall clock and Asia/Jerusalem timezone detection.",
    does: "Creates a briefing_edition for the day and opens collect jobs.",
    output: "Today’s briefing pipeline started.",
    failureMode: "Runs again until every collect job in the morning window has finished.",
  },
  briefing_collect_q: {
    what: "Parallel collect jobs for every active source in the morning window.",
    why: "Tens of sources in parallel, with worker leases and stuck-job detection.",
    input: "A source id and a date window.",
    does: "Runs connectors and writes evidence_discovery rows.",
    output: "Raw material for the edition collected.",
    failureMode: "A failed source retries with backoff and does not block the others.",
  },
  briefing_enrich_q: {
    what: "A stage that scans collected evidence and fetches full text for articles shorter than 1,000 characters.",
    why: "Feed summaries omit facts needed for accurate checking.",
    input: "Evidence from the last 36 hours.",
    does: "Extends usable text and stores a briefing_stage_artifact.",
    output: "An evidence pack with full text.",
    failureMode: "With no processable evidence the pipeline stops with no_processable_evidence.",
  },
  briefing_cluster_q: {
    what: "Groups evidence into story clusters by topic, entities, and source families.",
    why: "Puts independent reports of the same event side by side so corroboration can be examined.",
    input: "The enriched evidence pack.",
    does: "Creates briefing_story_cluster rows and maps evidence roles (primary, independent, syndicated).",
    output: "Structured story clusters.",
    failureMode: "With no clusters the pipeline stops with no_story_clusters.",
  },
  briefing_triage_model: {
    what: "A focused openai/gpt-5-nano call that picks up to eight stories, with first priority on anti-Israel claims and framings in the collected material.",
    why: "The edition has three stated jobs, in order: refute anti-Israel narratives, one regional geopolitical brief, and one interesting Israel story. Refutation is a goal of triage itself, not a filter after news selection.",
    input: "Story clusters and the public evidence pack.",
    does: "Returns a rigid JSON structure routing each story to narrative_watch or israel_update (up to 5 and 3). daily_brief is composed from the whole pack and is not chosen as a story; war_update is no longer selectable — security and operational material feeds the daily brief.",
    output: "Selected stories routed to narrative_watch or israel_update, plus an ai_run with an exact dollar cost.",
    failureMode: "A daily or monthly AI budget breach blocks the call immediately.",
  },
  briefing_draft_model: {
    what: "An openai/gpt-5-mini call that drafts the main brief and up to eight structured articles.",
    why: "Produces atomic claims, passages with explicit evidence links, and narrative-watch pieces that refute a claim rather than merely record it: the claim in full, why it is false or misleading, then the context promoters omit.",
    input: "The selected stories and the full evidence pack.",
    does: "Builds a complete edition: situation picture, key events, Israeli position, and items to watch.",
    output: "A full edition draft in which every record cites pack evidence — except at most one narrative_watch refutation that cites nothing and publishes as this organisation’s own analysis (evidenceBasis: analysis) with an explicit public mark.",
    failureMode: "Output that cites an evidence id missing from the pack fails Zod validation at once. A sourceless refutation that still cites any evidence — in a claim, a passage, or narrativeWatchDetails — also fails: all-or-nothing.",
  },
  briefing_quarantine: {
    what: "A legacy and operational quarantine table for malformed drafts and failed processing jobs.",
    why: "Keeps technically invalid payloads and failed jobs available for diagnosis without blocking valid generated editions.",
    input: "A malformed draft or a processing job that exhausted its retries.",
    does: "Records candidate_key, stage, reason, payload, and sets the edition to quarantined.",
    output: "A quarantine row for editorial review.",
    failureMode: "Only the affected invalid payload or failed job is retained for inspection.",
  },
  briefing_alert: {
    what: "Durable operational alerts with no classified content and fingerprint-based de-duplication.",
    why: "A briefing, budget, or collect failure is stored and emailed to editors.",
    input: "A critical error or threshold warning.",
    does: "Suppresses duplicate floods and sends mail via nodemailer.",
    output: "A durable in-system alert.",
    failureMode: "Critical alerts stay open until marked resolved.",
  },
  briefing_control: {
    what: "A singleton table that lets operators pause automatic publication with one switch.",
    why: "During an exceptional event or a special edit, collect and processing can keep running while public publish stops.",
    input: "A pause instruction from an editor or operator.",
    does: "Toggles automaticPublicationPaused between true and false.",
    output: "Immediate control of publish state.",
    failureMode: "While paused, outputs are saved as draft for human review instead of auto-publish.",
  },
  search_document: {
    what: "A table projecting items, evidence, and publications into a shape fit for multilingual and vector retrieval.",
    why: "Searching the model tables directly is slow and lacks dedicated Hebrew, English, and semantic indexes.",
    input: "A reindex event from the outbox.",
    does: "Builds word vectors (tsvector simple for Hebrew/Arabic, tsvector english), trigrams, and holds an embedding column.",
    output: "An up-to-date multi-dimensional retrieval index.",
    failureMode: "Embedding lag is measured as indexed_content_hash distinct from content_hash.",
  },
  cron_embed: {
    what: "A job every 30 minutes that computes embeddings for every document whose content changed.",
    why: "Lag is found by a simple signature compare: indexed_content_hash IS DISTINCT FROM content_hash, with no state queue that can stick.",
    input: "Documents whose content hash is stale.",
    does: "Produces a 1536-dimension vector via text-embedding-3-small and updates search_document.",
    output: "Fresh semantic vectors in pgvector.",
    failureMode: "If the process crashes, signatures stay different and the next tick retries safely.",
  },
  search_hybrid: {
    what: "A SQL function that runs four search arms in parallel: Hebrew/Arabic (simple), English, spelling (pg_trgm), and meaning (pgvector).",
    why: "Each method alone is blind to some cases (Arabic name transliterations, typos).",
    input: "A user query and the query vector.",
    does: "Returns up to four ranked result lists.",
    output: "Four ranked lists for fusion.",
    failureMode: "If the query vector is missing, the engine falls back to three-way lexical search.",
  },
  rrf_fusion: {
    what: "An algorithm that merges the four lists by relative rank: 1 / (60 + rank), never raw scores.",
    why: "Vector similarity and BM25 scores are not comparable, and calibration rots as the corpus grows. Pure rank does not.",
    input: "Four sorted lists from search_hybrid.",
    does: "Computes a weighted RRF score and returns the most relevant documents.",
    output: "One fused, precise result list.",
    failureMode: "The fused score is internal and is never shown to a reader as a confidence percent.",
  },
  ai_gateway: {
    what: "The only entry point for model calls (OpenAI / Anthropic / xAI).",
    why: "One choke point enforces budgets, classification checks, exact cost ledgers, and leak prevention.",
    input: "A model profile, a Zod output schema, and a data classification.",
    does: "Enforces limits, runs structured generation, and returns type-checked output.",
    output: "Structured output plus token and USD cost metadata.",
    failureMode: "A restricted or secret call is blocked in code before a single byte leaves the network.",
  },
  ai_run_ledger: {
    what: "An append-only ledger of every model call: input/output tokens, exact USD cost, latency, and input hash.",
    why: "No AI-produced change may enter the system without pointing at the ai_run_id that produced it.",
    input: "Execution metadata from the model call.",
    does: "Writes an immutable row.",
    output: "A unique ai_run_id.",
    failureMode: "A database constraint requires ai_run_id on every version created from a model suggestion.",
  },
  ai_suggestion: {
    what: "A separate table holding model suggestions (tags, summaries, evidence links) without touching live entities.",
    why: "A language model never writes straight into an item or assessment. It writes a suggestion and stops.",
    input: "Validated model output.",
    does: "Waits for a human editor to accept or reject.",
    output: "An isolated suggestion sitting at the human gate.",
    failureMode: "A rejected suggestion stays on the table as a record and never affects the public product.",
  },
  human_approval_gate: {
    what: "An editorial decision step: a qualified human accepts or rejects an AI suggestion.",
    why: "Acceptance goes through the ordinary versioning path with change source ai_suggestion_accepted and the run id.",
    input: "An editor decision (accept / reject).",
    does: "Updates the entity through the main versioning path with a full pointer to ai_run_id.",
    output: "A verified, attributed entity update.",
    failureMode: "There is no bypass that lets a model update an entity directly.",
  },
  chat_thread: {
    what: "An intelligence Q&A surface so analysts can ask questions of the verified store.",
    why: "Every answer must rest only on documents actually retrieved — no hallucination.",
    input: "An analyst question in free language.",
    does: "Runs hybrid retrieval first and records the documents found.",
    output: "A reasoned answer with checked citations.",
    failureMode: "The answer is non-streaming so a citation is never shown before it has been verified.",
  },
  chat_tool_run: {
    what: "An audit table recording every document id retrieval returned in that thread — before the model is asked.",
    why: "This is the hard set the citation guard uses to prove the model did not invent documents.",
    input: "The document list retrieval returned.",
    does: "Stores an immutable row of approved ids.",
    output: "An approved context for the model query.",
    failureMode: "A failed retrieval is logged as an error and cannot be cited.",
  },
  citation_guard: {
    what: "A database trigger that blocks saving a citation pointing at a document that was not in that thread’s successful retrieval.",
    why: "On a verification platform, a fabricated citation is the product failing at the thing it claims to do.",
    input: "An attempt to insert chat_citation.",
    does: "Confirms the cited document exists on the matching chat_tool_run.",
    output: "A citation that can be trusted.",
    failureMode: "The citation is rejected and filtered in the service so a good answer is not dropped.",
  },
  outbox: {
    what: "A table where intent to do later work is recorded in the same database transaction as the change itself.",
    why: "Publishing to a network queue after commit is not atomic. A crash in the gap loses work. If the write succeeded, the work will run.",
    input: "A change event on a versioned entity.",
    does: "Writes a topic and payload to outbox.",
    output: "Reliable delivery with no silent loss.",
    failureMode: "If the queue is down, rows wait for the next drain.",
  },
  cron_outbox_drain: {
    what: "A Vercel cron every 15 minutes that pulls up to 250 open outbox messages and pushes them onto a Vercel Queue.",
    why: "Drains the outbox and runs background consumers asynchronously. A full edition emits hundreds of rows, so the tick cap is 250 not 25 — at the old cap a story published at 07:00 would not be searchable until nearly 09:00.",
    input: "Waiting outbox rows.",
    does: "Sends up to 250 messages per tick to outbox.dispatch and marks them published.",
    output: "Messages flowing onto the queue.",
    failureMode: "A drain error leaves the messages in the table for the next tick.",
  },
  outbox_dispatch_q: {
    what: "A Vercel Queue endpoint that runs a consumer per topic: search.reindex, publication.cache-invalidate, email.notification, briefing.alert.",
    why: "Heavy async work stays off the request path.",
    input: "A queue message with a topic and entity payload.",
    does: "Routes to the matching consumer (for example search().reindex) and updates search documents. embedding.refresh was deleted entirely — no producer ever emitted it.",
    output: "A completed background job.",
    failureMode: "A poison message goes to the dead letter after max attempts. Retired topic item.detected stays registered as an empty consumer (tombstone), because rows written before retirement may still wait in the table, and an unregistered topic would crash dispatch on a retry loop.",
  },
  entity_version: {
    what: "One polymorphic version table for every entity, with a full snapshot on each change.",
    why: "Shows what the item said before, who changed it, from which source, and how to restore a prior version.",
    input: "Every create or update on a versioned entity.",
    does: "Stores a full snapshot, a serial version, and the change-source attribution.",
    output: "A complete change history.",
    failureMode: "Append-only — history cannot be deleted.",
  },
  audit_log: {
    what: "A detailed record of every significant action: who, what, when, and which object.",
    why: "Written inside the same transaction as the action, so a log row is never lost on a crash.",
    input: "Every core-service action.",
    does: "Also stores the actor’s name as frozen text, so it stays readable if the user is later deleted.",
    output: "A legal and journalistic audit trail.",
    failureMode: "Removing the trigger that writes audit_log fails dedicated mutation tests.",
  },
  rls_policy: {
    what: "Database permission policy for three roles: app_public, app_staff, app_service.",
    why: "A filter in application code can be forgotten on a new path. A database policy applies to every query, from everywhere, forever.",
    input: "The request’s database role.",
    does: "Automatically hides unpublished items and classified evidence from the public.",
    output: "Proven data isolation.",
    failureMode: "assertRole() in tests checks that the role actually switched in the transaction and did not run as table owner.",
  },
  public_reports: {
    what: "The only write path open to the public for reporting suspect content (link, text, screenshot).",
    why: "The public may INSERT only, with zero read grant, and a hashed IP for privacy.",
    input: "A public report form.",
    does: "Passes an atomic rate limit and is stored as received for staff triage.",
    output: "A report waiting for review.",
    failureMode: "A public reporter cannot read any row in the table.",
  },
  rate_limit_guard: {
    what: "A request counter in a fixed window, incremented inside Postgres in one atomic statement.",
    why: "An in-memory counter on a serverless instance does not work because instances come and go. A database counter actually holds.",
    input: "A hashed caller id.",
    does: "Increments the counter and rejects requests over 10 reports per hour.",
    output: "A fast allow or deny.",
    failureMode: "A rejected request is still counted, so a flood cannot retry forever.",
  },
};

export const GLOSSARY_COPY: Record<string, GlossaryTermCopy> = {
  "Outbox (Transactional Outbox)": {
    short: "A pattern that records every system event in the same database transaction as the change that caused it.",
    deep: "When an item is approved or published the system does not push to an external queue directly — a network crash would desynchronise the two. The event is written to the outbox table as part of the same database action, and a background job (cron/outbox-drain) pulls and delivers it safely.",
    example: "Approving an information item immediately writes an outbox row that later updates the search index and computes a vector embedding.",
  },
  "Blob Storage": {
    short: "Dedicated file storage (Vercel Blob) holding captured web pages and documents exactly as they were fetched.",
    deep: "To survive later edits or deletions on external sites, the system stores the original HTML or JSON in the cloud and computes a SHA-256 signature over it.",
    example: "A full Reuters news page (~240KB) stored with a signature that blocks later claims of forgery.",
  },
  "RLS (Row-Level Security)": {
    short: "A Postgres mechanism that restricts which rows a role may read or write.",
    deep: "Instead of trusting application code alone, the database itself blocks the public role (app_public) from reading drafts, internal assessments, or classified evidence, and allows only rows that have passed the official publish gate.",
    example: "An anonymous user cannot fetch an item an editor has not approved, even if they guess its id.",
  },
  canAssignVerdict: {
    short: "A pure function that requires at least two independent sources before a verified verdict is allowed.",
    deep: "To block human error and newsroom pressure, a claim cannot be marked verified unless at least two pieces of evidence from entirely different source families are linked to it (for example an Israeli agency and an independent international agency).",
    example: "Five sites quoting the same tweet count as one source, and the system will refuse a verified verdict.",
  },
  Quarantine: {
    short: "An operational isolation area for malformed payloads and processing jobs that exhaust their retries.",
    deep: "The editorial quality-review gate is disabled. This table remains only for technical failures such as invalid structured data or exhausted processing retries.",
    example: "An article that rests on a single non-official source without attribution and a written caveat is quarantined, and editors get an urgent alert.",
  },
  Triage: {
    short: "Fast classification and routing of news onto the edition’s three stated jobs.",
    deep: "A cheap, fast model (gpt-5-nano) walks dozens of news clusters and routes them in fixed priority: first anti-Israel claims and framings for refutation (narrative_watch, up to 5), then one interesting Israel story (israel_update, up to 3). The regional daily_brief is composed from the whole pack and is not chosen as a story. war_update is no longer selectable — security and operational material feeds the daily brief.",
    example: "140 daily reports filtered into two narrative refutations, one Israel story, and a daily brief that rests on the whole pack.",
  },
  "Narrative Watch (evidenceBasis: analysis)": {
    short: "A narrative_watch article that refutes an anti-Israel claim and publishes as this organisation’s own analysis, citing no sources.",
    deep: "Narrative watch exists to refute a claim, not only to record it, and sometimes the evidence pack has no external source that answers it. In that case the record may publish citing nothing — it cites everywhere, or it cites nowhere. evidenceBasis is derived in code from an empty evidence list and is not chosen by the model. At most one such refutation is allowed per edition, and every claim in it carries an explicit Lions of Zion editorial analysis attribution, a written caveat, and a conclusion of refuted / misleading / unsupported. The reader sees this on a title prefix, a disclosure paragraph, and an Evidence basis line.",
    example: "A repeating social-media claim that no outlet reported is answered by a refutation whose title starts with Analysis: and that rests on no external source.",
  },
  "Grounded RAG (Retrieval-Augmented Generation)": {
    short: "A chat architecture that requires the model to answer only from facts retrieved from the store.",
    deep: "In the intelligence chat the model may not invent facts from general memory. Every answer rests on items fetched at query time, and document ids are written to chat_tool_run before the model replies.",
    example: "A question about 7 October is answered only from official testimony documents retrieved from the database.",
  },
  "Citation Guard": {
    short: "A SQL trigger that checks every citation in a chat answer was actually retrieved in that query.",
    deep: "If the model hallucinates a document that was not in the search results it was given, the database trigger chat_citation_must_be_retrieved rejects the citation and stops the user being misled.",
    example: "The model tries to cite a fictional document; the database blocks the link and returns only real citations.",
  },
  "RRF (Reciprocal Rank Fusion)": {
    short: "A ranking algorithm that merges results from four search engines into one quality ranking.",
    deep: "The system runs four queries in parallel: lexical Hebrew (simple), English (stemmed), trigrams for typos, and semantic vectors. An RRF formula with k=60 merges the four lists by rank position.",
    example: "A document second in the Hebrew list and third in the semantic list receives a top fused score.",
  },
  pgvector: {
    short: "A Postgres extension that stores and compares 1536-dimension mathematical vectors.",
    deep: "Every article or testimony is encoded as 1536 numbers representing its meaning. Cosine-distance search finds similar pieces even when they use completely different words.",
    example: "A search for ground incursion finds pieces about an infantry invasion because of semantic similarity.",
  },
  "Cron (Vercel Crons)": {
    short: "A cloud scheduler that hits server endpoints on a fixed timetable.",
    deep: "Five central crons: source ingest every 30 minutes, daily brief at 07:00, outbox drain every 15 minutes, vector embeddings every 30 minutes, and daily maintenance.",
    example: "At 07:00 exactly a signed call starts the daily edition pipeline.",
  },
  "Two-Human Rule": {
    short: "A hard rule that the person who wrote an item cannot approve or publish it.",
    deep: "The SQL trigger enforce_publish_gate checks that the writer or editor of the information item is a different person from the editor who approves it, and that both are real people rather than bots or AI agents.",
    example: "An editor trying to approve an item they created is blocked at the database with a permission error.",
  },
  "Circuit Breaker": {
    short: "A mechanism that pauses calls to external sources after a run of consecutive failures.",
    deep: "If a news site does not respond or errors five times in a row, the system disables it temporarily so the ingest chain is not jammed and network budget is not wasted.",
    example: "An RSS feed whose site is down is auto-disabled until an operator reviews it.",
  },
  "GDELT Project": {
    short: "An international project that monitors and analyses tens of thousands of news sources in near-real time.",
    deep: "The GDELT connector scans global reporting on Israel, the Middle East, and information warfare, and surfaces new narratives as they spread.",
    example: "Fifty new South American reports on the war found within minutes of publication.",
  },
  "Evidence Provenance": {
    short: "A full historical record of every hop an evidence item took from capture to publication.",
    deep: "Each piece of evidence carries the capturer (human or bot), timestamp, original URL, SHA-256 of the raw file, and every confirmation performed on it.",
    example: "Forensic proof that a screenshot of a Hamas document was captured at a given time and was not graphically edited.",
  },
};

export function nodeInspectorCopy(nodeId: string): NodeInspectorCopy | null {
  return NODE_COPY[nodeId] ?? null;
}

export function glossaryTermCopy(termEn: string): GlossaryTermCopy | null {
  return GLOSSARY_COPY[termEn] ?? null;
}

export function kindLabel(kind: NodeKind | string): string {
  return KIND_LABELS[kind as NodeKind] ?? kind;
}
