/**
 * Generates the stylesheet entry the converter appends (`cfg.cssEntry`).
 *
 * Why this exists rather than a committed CSS file:
 *
 *  1. `app/globals.css` carries the whole V2 token system and is the single
 *     source of truth. Copying it into a committed sync file would rot the
 *     moment someone edits the real one, so it is inlined at build time
 *     instead — read fresh, never duplicated in git.
 *  2. The token layer resolves its three faces through `--font-newsreader`,
 *     `--font-plex-sans` and `--font-geist-mono`, which NOTHING in the
 *     stylesheet defines: in the real app `next/font/google` injects them onto
 *     `<html>` at build time. Undefined, `var()` makes the whole declaration
 *     invalid at computed-value time, so every face silently degrades. This
 *     binds them.
 *  3. The `@font-face` rules are INLINED, not pulled in with `@import
 *     url(...)`. The converter appends this file to the END of
 *     `_ds_bundle.css`, and a CSS `@import` after any style rule is invalid and
 *     silently ignored by every browser — measured: it landed at line 2887 of
 *     2899 and would never have loaded. `@font-face` is order-independent.
 *
 * Run before `package-build.mjs`. Network access is required once, to fetch
 * the font faces from Google; the result is written into the generated file so
 * the bundle itself has no build-time dependency on the font host.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const OUT = resolve(ROOT, '.design-sync/.cache/ds-styles.css');

const FAMILIES =
  'family=Newsreader:ital,opsz,wght@0,6..72,200..800;1,6..72,200..800' +
  '&family=IBM+Plex+Sans:ital,wght@0,400;0,500;0,600;1,400;1,500;1,600' +
  '&family=Geist+Mono:wght@100..900' +
  '&family=Cinzel:wght@400..700';

/* A modern UA is what makes Google return woff2 + unicode-range subsets
   rather than legacy ttf. */
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36';

const res = await fetch(`https://fonts.googleapis.com/css2?${FAMILIES}&display=swap`, {
  headers: { 'User-Agent': UA },
});
if (!res.ok) throw new Error(`[FONTS] Google Fonts returned ${res.status}`);
const faces = await res.text();

const faceCount = (faces.match(/@font-face/g) ?? []).length;
const families = [...new Set([...faces.matchAll(/font-family:\s*'([^']+)'/g)].map((m) => m[1]))];
const EXPECTED = ['Newsreader', 'IBM Plex Sans', 'Geist Mono', 'Cinzel'];
const missing = EXPECTED.filter((f) => !families.includes(f));
if (missing.length) throw new Error(`[FONTS] families missing from the response: ${missing.join(', ')}`);

const globals = readFileSync(resolve(ROOT, 'app/globals.css'), 'utf8');

const out = `/* GENERATED by .design-sync/build-styles.mjs — do not edit.
   ${faceCount} @font-face rules for ${families.join(', ')}, then app/globals.css
   inlined verbatim, then the --font-* bindings the token layer expects. */

${faces}

${globals}

/* Bind the families above to the variable names app/globals.css already reads.
   In the app these come from next/font/google; outside Next they must be
   supplied or every --face-* token resolves to an invalid value. */
:root {
  --font-newsreader: 'Newsreader';
  --font-plex-sans: 'IBM Plex Sans';
  --font-geist-mono: 'Geist Mono';
  --font-cinzel: 'Cinzel';
  --font-geist-sans: 'IBM Plex Sans';
}

/* ── Guard against the app shell ──────────────────────────────────────────
   Inert as of 2026-08-27, and kept deliberately.

   \`app/globals.css\` used to set \`html, body { height: 100%; overflow: hidden }\`
   for the fixed particle scene, which would have made every design built with
   this system unscrollable — content below the fold unreachable, with nothing
   downstream to catch it. The document-scroll conversion removed those rules;
   \`globals.css\` now sets only \`width\` and \`min-height\` on \`html, body\`, and the
   sideways clip lives on \`html:has([data-home-scroll])\`, which cannot match a
   DS design.

   So these declarations override nothing today. They stay because the app
   shell could reacquire those rules, the failure would be silent, and the cost
   of the guard is three declarations that lose to any real rule anyway. Do not
   read this block as evidence that globals.css is still hostile. */
html, body {
  height: auto;
  min-height: 100%;
  overflow: visible;
}
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out);
console.error(
  `  ds-styles: ${faceCount} @font-face (${families.join(', ')}) + globals.css (${(globals.length / 1024).toFixed(1)} KB) → ${OUT.replace(ROOT + '/', '')}`,
);
