/** Public architecture, not runtime telemetry. Keep route differences visible.
 * Sources: briefing/service.ts, external-publish.ts, codex-import.ts,
 * publications/service.ts, chat/service.ts, and the public archive routes.
 */
export const PIPELINE_STAGES = [
  { number: "01", name: "Collect", job: "collect" },
  { number: "02", name: "Enrich", job: "enrich" },
  { number: "03", name: "Cluster", job: "cluster" },
  { number: "04", name: "Triage", job: "triage" },
  { number: "05", name: "Draft", job: "draft" },
  { number: "06", name: "Quality", job: "quality" },
  { number: "07", name: "Publish", job: "publish" },
] as const;

export const SYSTEM_NODES = [
  { id: "sources", name: "Open sources", label: "Feeds · queries · public reporting", x: 0, y: 50,
    detail: "Configured sources bring public material into the system. Collection records what was retrieved; it does not establish that a source’s claim is true.", input: "Configured feeds and discovery queries", output: "Retrieved material for enrichment" },
  { id: "packages", name: "Submitted editions", label: "Research prepared outside the pipeline", x: 0, y: 230,
    detail: "An edition can arrive as a structured package with its source references. The checked-package route evaluates quality; the direct Codex import is a separate publishing path.", input: "Edition content and source references", output: "Evidence records and publication inputs" },
  { id: "research", name: "Research & documentation", label: "Claims · records · editorial work", x: 0, y: 410,
    detail: "Research can create information items and assessments. Archive documentation is a separate public surface: it should not be mistaken for a product of the automated briefing jobs.", input: "Research material and documented records", output: "Items, assessments, or archive material" },
  { id: "evidence", name: "Evidence & provenance", label: "Where the material came from", x: 380, y: 50,
    detail: "Evidence retains source references and provenance. Named source families help distinguish origins; family assignments and copied reporting still require care. A stored source is not a verified claim.", input: "Collected or submitted source material", output: "Evidence IDs, URLs and provenance records" },
  { id: "analysis", name: "Context & assessment", label: "What can actually be established?", x: 380, y: 230,
    detail: "Briefing jobs cluster, triage and draft from the available material. The information-item model separately supports assessments with explicit confidence dimensions and known gaps. These are related, not identical workflows.", input: "Evidence and the question being examined", output: "Draft reporting or a recorded assessment" },
  { id: "quality", name: "Publication checks", label: "Checks depend on the publishing path", x: 380, y: 410,
    detail: "The automated briefing and checked-package paths evaluate source, content and citation requirements. Direct imports follow a different path. Passing automated checks is not proof that every statement is true.", input: "Draft content and its evidence references", output: "Recorded check results; a decision to proceed or stop" },
  { id: "publication", name: "The public record", label: "Briefs · updates · narrative reporting", x: 760, y: 50,
    detail: "Published articles have public URLs and publication metadata. Sourced reporting and explicitly labelled analysis have different evidence bases. A record can be corrected or withdrawn; publication is not a guarantee of certainty.", input: "Publication content and path-specific provenance", output: "Public articles, references and timestamps" },
  { id: "access", name: "Find. Read. Ask.", label: "Search & conversation", x: 760, y: 230,
    detail: "Search makes indexed public content discoverable. Ask can retrieve site documents and cite them; it can also use X search when available. An assistant response is not itself a published finding.", input: "Indexed content and the reader’s question", output: "Search results or an answer with available citations" },
  { id: "archive", name: "The October 7 archive", label: "A distinct documentation surface", x: 760, y: 410,
    detail: "The archive gives documented material its own structured, navigable home. It sits alongside current reporting, rather than being generated by the daily briefing chain.", input: "Archive records and documentation", output: "Browsable records with their own context" },
] as const;
export type SystemNodeId = (typeof SYSTEM_NODES)[number]["id"];

export const PIPELINE_ROUTES: readonly {
  id: string; name: string; subject: string; steps: readonly SystemNodeId[]; note: string;
}[] = [
  { id: "briefing", name: "Automated briefing", subject: "From collected material to a sourced edition.",
    steps: ["sources", "evidence", "analysis", "quality", "publication", "access"],
    note: "The implemented job chain is collect → enrich → cluster → triage → draft → quality → publish. This illustration does not assert that a run is active or an edition is on schedule." },
  { id: "package", name: "Checked package", subject: "Research can enter as a prepared edition, not just as a collected signal.",
    steps: ["packages", "evidence", "quality", "publication", "access"],
    note: "The external-package publisher resolves source references, evaluates quality requirements, then creates public output or drafts according to publication controls." },
  { id: "import", name: "Direct import", subject: "A separate import path, with a different set of controls.",
    steps: ["packages", "evidence", "publication", "access"],
    note: "The Codex import records sources and publication provenance, but does not run the same quality evaluator as the checked-package path. The diagram deliberately does not draw a check it does not perform." },
  { id: "claim", name: "Claim research", subject: "Keep a claim, the material behind it, and the assessment distinct.",
    steps: ["research", "evidence", "analysis", "publication", "access"],
    note: "A conceptual editorial route: information items and assessments are separate entities from briefing drafts. An assessment does not automatically become a public article." },
  { id: "archive", name: "Documentation", subject: "Preserve documented material in a public archive.",
    steps: ["research", "archive"],
    note: "The October 7 archive is a separate publishing surface. This route does not imply that an archive entry is generated by the briefing pipeline or indexed by every retrieval tool." },
];

/** Explicit connectors make bypasses legible instead of forcing every route through a gate. */
export const SYSTEM_EDGES: readonly { from: SystemNodeId; to: SystemNodeId; path: string }[] = [
  { from: "sources", to: "evidence", path: "M240 94 H380" },
  { from: "packages", to: "evidence", path: "M240 274 H300 V94 H380" },
  { from: "research", to: "evidence", path: "M240 454 H276 V94 H380" },
  { from: "evidence", to: "analysis", path: "M500 138 V230" },
  { from: "evidence", to: "quality", path: "M620 94 H650 V454 H620" },
  { from: "analysis", to: "quality", path: "M500 318 V410" },
  { from: "quality", to: "publication", path: "M620 454 H698 V94 H760" },
  { from: "evidence", to: "publication", path: "M620 94 H760" },
  { from: "analysis", to: "publication", path: "M620 274 H674 V94 H760" },
  { from: "publication", to: "access", path: "M880 138 V230" },
  { from: "research", to: "archive", path: "M120 498 V530 H880 V498" },
];
