/** Public architecture, not runtime telemetry. Keep provenance paths visible. */
export const PIPELINE_STAGES = [
  { number: "01", name: "Collect", job: "collect" },
  { number: "02", name: "Preserve provenance", job: "evidence" },
  { number: "03", name: "Prepare editorial work", job: "editorial" },
  { number: "04", name: "Apply publishing rules", job: "publish" },
  { number: "05", name: "Index the public record", job: "search" },
] as const;

export const SYSTEM_NODES = [
  { id: "sources", name: "Open sources", label: "Feeds · queries · public reporting", x: 0, y: 50,
    detail: "Configured sources bring public material into the system. Collection records what was retrieved; it does not establish that a source’s claim is true and it does not publish an article.", input: "Configured feeds and discovery queries", output: "Retrieved material for evidence work" },
  { id: "packages", name: "Editorial runs", label: "Structured reporting with machine provenance", x: 0, y: 230,
    detail: "A machine-authored editorial run can prepare structured reporting with source references and placement decisions. It is identified through machine provenance; AI assists the work but is never evidence.", input: "Editorial material and source references", output: "Publication inputs with provenance" },
  { id: "research", name: "Research & documentation", label: "Claims · records · human investigation", x: 0, y: 410,
    detail: "Research can create information items and human assessments. Archive documentation is a separate public surface, with its own provenance path.", input: "Research material and documented records", output: "Items, assessments, or archive material" },
  { id: "evidence", name: "Evidence & provenance", label: "Where the material came from", x: 380, y: 50,
    detail: "Evidence retains source references and provenance. Named source families help distinguish origins; family assignments and copied reporting still require care. A stored source is not a verified claim.", input: "Collected, submitted or researched material", output: "Evidence IDs, URLs and provenance records" },
  { id: "analysis", name: "Context & assessment", label: "What can actually be established?", x: 380, y: 230,
    detail: "Human investigations can turn evidence into an assessment with explicit confidence dimensions and known gaps. An assessment is distinct from a machine-authored editorial run and does not automatically become an article.", input: "Evidence and the question being examined", output: "A recorded assessment or reporting context" },
  { id: "quality", name: "Publishing safeguards", label: "Rules depend on the provenance path", x: 380, y: 410,
    detail: "Machine-authored editorial runs are governed by server-enforced rules and recorded machine provenance. Human assessments retain their separate review gate. These safeguards support accountability; they do not prove every statement true.", input: "Content and its provenance", output: "A recorded decision to proceed or stop" },
  { id: "publication", name: "The public record", label: "Reporting · updates · documented material", x: 760, y: 50,
    detail: "Published records have public URLs, dates and provenance appropriate to their path. Sourced reporting and explicitly labeled analysis have different evidence bases. A record can be corrected or withdrawn; publication is not a guarantee of certainty.", input: "Publication content and path-specific provenance", output: "Public articles, references and timestamps" },
  { id: "access", name: "Find. Read. Ask.", label: "Search & conversation", x: 760, y: 230,
    detail: "Search makes indexed public content discoverable. Ask can retrieve site documents and cite them; an assistant response is not itself a published finding.", input: "Indexed content and the reader’s question", output: "Search results or an answer with available citations" },
  { id: "archive", name: "The October 7 archive", label: "A distinct documentation surface", x: 760, y: 410,
    detail: "The archive gives documented material its own structured, navigable home. It sits alongside current reporting rather than being generated by the editorial delivery path.", input: "Archive records and documentation", output: "Browsable records with their own context" },
] as const;
export type SystemNodeId = (typeof SYSTEM_NODES)[number]["id"];

export const PIPELINE_ROUTES: readonly {
  id: string; name: string; subject: string; steps: readonly SystemNodeId[]; note: string;
}[] = [
  { id: "editorial", name: "Machine-authored editorial run", subject: "Structured reporting with sources, provenance and a durable publication path.",
    steps: ["packages", "evidence", "quality", "publication", "access"],
    note: "The system records machine provenance and applies server-enforced publishing rules. New material can update an existing canonical story rather than create a second article." },
  { id: "collection", name: "Collection & evidence", subject: "Collect public material without turning collection into authorship.",
    steps: ["sources", "evidence", "analysis"],
    note: "Collection supplies material for discovery, research and evidence work. It never composes or publishes an editorial record on its own." },
  { id: "assessment", name: "Human assessment", subject: "Keep a claim, the material behind it, and the assessment distinct.",
    steps: ["research", "evidence", "analysis", "quality", "publication", "access"],
    note: "A human assessment follows its own review path. It is not an automatic result of collection or a machine-authored editorial run." },
  { id: "archive", name: "Documentation", subject: "Preserve documented material in a public archive.",
    steps: ["research", "archive"],
    note: "The October 7 archive is a separate publishing surface. This route does not imply that an archive entry is generated by editorial automation or indexed by every retrieval tool." },
];

/** Explicit connectors make bypasses legible instead of forcing every route through a gate. */
export const SYSTEM_EDGES: readonly { from: SystemNodeId; to: SystemNodeId; path: string }[] = [
  { from: "sources", to: "evidence", path: "M240 94 H380" },
  { from: "packages", to: "evidence", path: "M240 274 H300 V94 H380" },
  { from: "research", to: "evidence", path: "M240 454 H276 V94 H380" },
  { from: "evidence", to: "analysis", path: "M500 138 V230" },
  { from: "evidence", to: "quality", path: "M620 94 H650 V454 H620" },
  { from: "analysis", to: "quality", path: "M500 318 V410" },
  { from: "quality", to: "publication", path: "M620 454 H698 V94 H760" },
  { from: "evidence", to: "publication", path: "M620 94 H760" },
  { from: "analysis", to: "publication", path: "M620 274 H674 V94 H760" },
  { from: "publication", to: "access", path: "M880 138 V230" },
  { from: "research", to: "archive", path: "M120 498 V530 H880 V498" },
];
